const ERR_DUPLICATED_EMAIL = 'ERR_DUPLICATED_EMAIL';
const ERR_USER_NOT_FOUND = 'ERR_USER_NOT_FOUND';
const ERR_INVALID_PASSWORD = 'ERR_INVALID_PASSWORD';
const ERR_INVALID_TOKEN = 'TOKEN_ERROR';

module.exports = {
  ERR_DUPLICATED_EMAIL,
  ERR_USER_NOT_FOUND,
  ERR_INVALID_PASSWORD,
  ERR_INVALID_TOKEN,
};
